import Head from 'next/head'
import Image from 'next/image'
import TopBar from '../../../src/components/navBar'
import SubmitAssignmentsContainer from '../../../src/container/Assignments/Submit'
import ViewAssignmentsContainer from '../../../src/container/Assignments/View'

export default function ViewAssignments() {

  return (
    <div>
      <Head>
        <title>View Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar back={true}>
        <main>
          <ViewAssignmentsContainer />
        </main>
      </TopBar>
    </div>
  )
}