import Head from 'next/head'
import Image from 'next/image'
import TopBar from '../../../src/components/navBar'
import SubmitAssignmentsContainer from '../../../src/container/Assignments/Submit'

export default function SubmitAssignments() {

  return (
    <div>
      <Head>
        <title>Submit Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar>
        <main>
          <SubmitAssignmentsContainer/>
        </main>
      </TopBar>
    </div>
  )
}