import Head from 'next/head'
import Image from 'next/image'
import TopBar from '../../src/components/navBar'
import AssignmentsContainer from '../../src/container/Assignments'
import AttendanceContainer from '../../src/container/Attendance'
import DiscussionsContainer from '../../src/container/Discussions'

export default function Discussions() {
  return (
    <div>
      <Head>
        <title>Discussions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar>
        <main>
          <DiscussionsContainer/>
        </main>
      </TopBar>
    </div>
  )
}