import Head from 'next/head'
import Image from 'next/image'
import NewAssignmentsContainer from '../../../src/container/Assignments/New'
import TopBar from '../../../src/components/navBar'

export default function NewAssignments() {
  return (
    <div>
      <Head>
        <title>New Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar>
        <main>
          <NewAssignmentsContainer />
        </main>
      </TopBar>
    </div>
  )
}
