import Head from 'next/head'
import Image from 'next/image'
import ScheduleCalender from '../../src/components/Schedule/calender'
import ScheduleContainer from '../../src/container/Schedule'
import TopBar from '../../src/components/navBar'
import DoubtsContainer from '../../src/container/Doubts'

export default function Schedule() {
  return (
    <div>
      <Head>
        <title>Doubts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar>
        <main>
          <DoubtsContainer/>
        </main>
      </TopBar>
    </div>
  )
}
