import Head from 'next/head'
import Image from 'next/image'
import TopBar from '../../src/components/navBar'
import AssignmentsContainer from '../../src/container/Assignments'
import AttendanceContainer from '../../src/container/Attendance'

export default function Schedule() {
  return (
    <div>
      <Head>
        <title>Attendance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar>
        <main>
          <AttendanceContainer/>
        </main>
      </TopBar>
    </div>
  )
}